#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Copy kernel + initramfs from the live ISO to the installed system.
archiso stores them outside the squashfs, so unpackfs alone doesn't bring
them across."""

import os
import shutil
import subprocess
import libcalamares

def pretty_name():
    return "Copying kernel and initramfs..."

def get_root_mount_point():
    return libcalamares.globalstorage.value("rootMountPoint")

def find_kernel_source():
    possible_paths = [
        "/run/archiso/bootmnt/shedos/boot/vmlinuz-shedos-kernel",
        "/run/archiso/bootmnt/shedos/boot/x86_64/vmlinuz-shedos-kernel",
        "/run/archiso/copytoram/shedos/boot/vmlinuz-shedos-kernel",
        "/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-shedos-kernel",
        "/run/archiso/bootmnt/arch/boot/vmlinuz-shedos-kernel",
        "/usr/lib/modules/*/vmlinuz",  # last-resort fallback
    ]

    for path in possible_paths:
        if "*" in path:
            import glob
            matches = glob.glob(path)
            if matches:
                return matches[0]
        elif os.path.exists(path):
            return path

    return None

def find_initramfs_source():
    possible_paths = [
        "/run/archiso/bootmnt/shedos/boot/initramfs-shedos-kernel.img",
        "/run/archiso/bootmnt/shedos/boot/x86_64/initramfs-shedos-kernel.img",
        "/run/archiso/copytoram/shedos/boot/initramfs-shedos-kernel.img",
        "/run/archiso/bootmnt/arch/boot/x86_64/initramfs-shedos-kernel.img",
        "/run/archiso/bootmnt/arch/boot/initramfs-shedos-kernel.img",
    ]

    for path in possible_paths:
        if os.path.exists(path):
            return path

    return None

def run():
    root_mount_point = get_root_mount_point()

    if not root_mount_point:
        return ("Failed to get root mount point", "Could not determine where the system is installed")

    boot_dir = os.path.join(root_mount_point, "boot")
    os.makedirs(boot_dir, exist_ok=True)

    kernel_src = find_kernel_source()
    if kernel_src:
        kernel_dst = os.path.join(boot_dir, "vmlinuz-shedos-kernel")
        try:
            libcalamares.utils.debug(f"Copying kernel from {kernel_src} to {kernel_dst}")
            shutil.copy2(kernel_src, kernel_dst)
            libcalamares.utils.debug("Kernel copied successfully")
        except Exception as e:
            return (f"Failed to copy kernel: {e}", f"Source: {kernel_src}, Destination: {kernel_dst}")
    else:
        debug_info = ""
        for path in ["/run/archiso", "/run/archiso/bootmnt", "/run/archiso/bootmnt/shedos"]:
            if os.path.exists(path):
                try:
                    contents = os.listdir(path)
                    debug_info += f"\n{path}: {contents}"
                except:
                    debug_info += f"\n{path}: (could not list)"
            else:
                debug_info += f"\n{path}: (does not exist)"

        return ("Kernel not found", f"Could not find vmlinuz-shedos-kernel in any expected location.{debug_info}")

    initramfs_src = find_initramfs_source()
    if initramfs_src:
        initramfs_dst = os.path.join(boot_dir, "initramfs-shedos-kernel.img")
        try:
            libcalamares.utils.debug(f"Copying initramfs from {initramfs_src} to {initramfs_dst}")
            shutil.copy2(initramfs_src, initramfs_dst)
            libcalamares.utils.debug("Initramfs copied successfully")
        except Exception as e:
            return (f"Failed to copy initramfs: {e}", f"Source: {initramfs_src}, Destination: {initramfs_dst}")
    else:
        libcalamares.utils.debug("Initramfs not found - will be generated by initcpio module")

    fallback_paths = [
        "/run/archiso/bootmnt/shedos/boot/initramfs-shedos-kernel-fallback.img",
        "/run/archiso/bootmnt/arch/boot/x86_64/initramfs-shedos-kernel-fallback.img",
    ]
    for fallback_src in fallback_paths:
        if os.path.exists(fallback_src):
            fallback_dst = os.path.join(boot_dir, "initramfs-shedos-kernel-fallback.img")
            try:
                shutil.copy2(fallback_src, fallback_dst)
                libcalamares.utils.debug("Fallback initramfs copied")
            except:
                pass
            break

    return None
