#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# ShedOS Kernel Copy Module
# Copies the kernel and initramfs from the live ISO to the installed system
# This is needed because archiso stores the kernel outside the squashfs

import os
import shutil
import subprocess
import libcalamares

def pretty_name():
    return "Copying kernel and initramfs..."

def get_root_mount_point():
    """Get the root mount point from global storage."""
    return libcalamares.globalstorage.value("rootMountPoint")

def find_kernel_source():
    """Find the kernel in the live environment."""
    # Possible locations for the kernel
    possible_paths = [
        "/run/archiso/bootmnt/shedos/boot/vmlinuz-linux",
        "/run/archiso/bootmnt/shedos/boot/x86_64/vmlinuz-linux",
        "/run/archiso/copytoram/shedos/boot/vmlinuz-linux",
        "/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-linux",
        "/run/archiso/bootmnt/arch/boot/vmlinuz-linux",
        "/usr/lib/modules/*/vmlinuz",  # Fallback - kernel in modules dir
    ]

    for path in possible_paths:
        if "*" in path:
            # Handle glob pattern
            import glob
            matches = glob.glob(path)
            if matches:
                return matches[0]
        elif os.path.exists(path):
            return path

    return None

def find_initramfs_source():
    """Find the initramfs in the live environment."""
    possible_paths = [
        "/run/archiso/bootmnt/shedos/boot/initramfs-linux.img",
        "/run/archiso/bootmnt/shedos/boot/x86_64/initramfs-linux.img",
        "/run/archiso/copytoram/shedos/boot/initramfs-linux.img",
        "/run/archiso/bootmnt/arch/boot/x86_64/initramfs-linux.img",
        "/run/archiso/bootmnt/arch/boot/initramfs-linux.img",
    ]

    for path in possible_paths:
        if os.path.exists(path):
            return path

    return None

def run():
    """Main entry point for the module."""
    root_mount_point = get_root_mount_point()

    if not root_mount_point:
        return ("Failed to get root mount point", "Could not determine where the system is installed")

    boot_dir = os.path.join(root_mount_point, "boot")

    # Ensure boot directory exists
    os.makedirs(boot_dir, exist_ok=True)

    # Find and copy kernel
    kernel_src = find_kernel_source()
    if kernel_src:
        kernel_dst = os.path.join(boot_dir, "vmlinuz-linux")
        try:
            libcalamares.utils.debug(f"Copying kernel from {kernel_src} to {kernel_dst}")
            shutil.copy2(kernel_src, kernel_dst)
            libcalamares.utils.debug("Kernel copied successfully")
        except Exception as e:
            return (f"Failed to copy kernel: {e}", f"Source: {kernel_src}, Destination: {kernel_dst}")
    else:
        # List what's actually in /run/archiso for debugging
        debug_info = ""
        for path in ["/run/archiso", "/run/archiso/bootmnt", "/run/archiso/bootmnt/shedos"]:
            if os.path.exists(path):
                try:
                    contents = os.listdir(path)
                    debug_info += f"\n{path}: {contents}"
                except:
                    debug_info += f"\n{path}: (could not list)"
            else:
                debug_info += f"\n{path}: (does not exist)"

        return ("Kernel not found", f"Could not find vmlinuz-linux in any expected location.{debug_info}")

    # Find and copy initramfs
    initramfs_src = find_initramfs_source()
    if initramfs_src:
        initramfs_dst = os.path.join(boot_dir, "initramfs-linux.img")
        try:
            libcalamares.utils.debug(f"Copying initramfs from {initramfs_src} to {initramfs_dst}")
            shutil.copy2(initramfs_src, initramfs_dst)
            libcalamares.utils.debug("Initramfs copied successfully")
        except Exception as e:
            return (f"Failed to copy initramfs: {e}", f"Source: {initramfs_src}, Destination: {initramfs_dst}")
    else:
        libcalamares.utils.debug("Initramfs not found - will be generated by initcpio module")

    # Copy fallback initramfs if it exists
    fallback_paths = [
        "/run/archiso/bootmnt/shedos/boot/initramfs-linux-fallback.img",
        "/run/archiso/bootmnt/arch/boot/x86_64/initramfs-linux-fallback.img",
    ]
    for fallback_src in fallback_paths:
        if os.path.exists(fallback_src):
            fallback_dst = os.path.join(boot_dir, "initramfs-linux-fallback.img")
            try:
                shutil.copy2(fallback_src, fallback_dst)
                libcalamares.utils.debug("Fallback initramfs copied")
            except:
                pass  # Not critical
            break

    return None  # Success
