# Stub for libcalamares.utils — see ../__init__.pyi for why this exists.
from typing import Any

def debug(msg: str) -> None: ...
def warning(msg: str) -> None: ...
def check_target_env_call(command: Any, *args: Any, **kwargs: Any) -> Any: ...
def target_env_call(command: Any, *args: Any, **kwargs: Any) -> Any: ...
