# ShedOS Keyboard Module Configuration

# Default keyboard model and layout
xOrgConfFileName: "/etc/X11/xorg.conf.d/00-keyboard.conf"

convertedKeymapPath: "/lib/kbd/keymaps/xkb"

# Write to vconsole.conf for virtual console
writeEtcDefaultKeyboard: true
