# ShedOS Netinstall Configuration
# Profile selection using netinstall module
---
groupsUrl:
  - file:///etc/calamares/modules/netinstall.yaml

required: false
label:
    sidebar: "Installation Profile"
    title: "Choose Installation Profile"
    title[es]: "Elegir Perfil de Instalación"
