# Mount ESP before bootloader installation
# Calamares mount module doesn't mount ESP, only root + subvolumes
dontChroot: true
timeout: 60
script:
    - "-mkdir -p @@ROOT@@/boot/efi"
    - "-mount /dev/vda1 @@ROOT@@/boot/efi"
