dontChroot: true
timeout: 120
script:
    - "echo DEBUG_START > @@ROOT@@/root/debug.log"
    - "-mount >> @@ROOT@@/root/debug.log 2>&1"
    - "-ls -la @@ROOT@@/boot/efi >> @@ROOT@@/root/debug.log 2>&1"
    - "-lsblk -f >> @@ROOT@@/root/debug.log 2>&1"
    - "echo DEBUG_END >> @@ROOT@@/root/debug.log"
